local Globals = {
    grid = nil,
    gameMenu = nil,
    realScreenWidth = nil,
    realScreenHeight = nil,
    realScreenInnerWidth = nil,
    realScreenInnerHeight = nil,
    realScreenXOffset = 0,
    realScreenYOffset = 0,
    screenWidth = 1920,
    screenHeight = 1080,
    screenScalar = 1,
    mouseX = 0,
    mouseY = 0,
    heldTile = "conveyer",
    heldTileRotation = 0,
    dt = 0,
    simulation = nil,
    backgroundOpacity = 0,
    loggerActive = true,
    drawFutureItems = false,
    solidTileSet = {wall = true, piston = true, welder = true, sensor = true},
    allRotations = {{rotation = 0, xOffset = 1, yOffset = 0}, {rotation = 2, xOffset = -1, yOffset = 0}, {rotation = 1, xOffset = 0, yOffset = -1}, {rotation = 3, xOffset = 0, yOffset = 1}},
    selectedLevel = nil,
}
return Globals